<?php

/**
 * @file
 * Provides an formtool of a webform handler.
 */

use Drupal\Component\Plugin\Exception\PluginException;
use Drupal\webform\Entity\Webform;

/**
 * Implements hook_theme().
 */
function webform_formtool_handler_theme(): array {
  return [
    'webform_formtool_handler_summary' => [
      'variables' => ['settings' => NULL, 'handler' => []],
    ],
    'submission_print' => [
      'variables' => [
        'submission' => NULL,
        'form' => NULL,
        'id' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_mail().
 */
function webform_formtool_handler_mail($key, &$message, $params) {
  $options = [
    'langcode' => $message['langcode'],
  ];

  switch ($key) {
    case 'submission_email_notify':
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = t('New submission for @title', ['@title' => $params['form_title']], $options);
      $message['body'][] = $params['message'];
      break;
  }
}

/**
 * Implements hook_entity_presave().
 */
function webform_formtool_handler_webform_presave(Webform $entity) {

  // Make sure we have correct permissions set to webforms.
  // Let's just override anything set in the UI.
  // Load settings.
  $thirdPartySettings = $entity->getThirdPartySettings('form_tool_webform_parameters');

  // let's default permissions to none.
  $acc = [];

  // Create basic permissions to all forms.
  $acc['create']['users'] = [];
  $acc['create']['permissions'] = [];

  $acc['view_any']['roles'] = [
    'admin',
  ];
  $acc['view_any']['users'] = [];
  $acc['view_any']['permissions'] = [];

  $acc['update_any']['roles'] = [
    'admin',
  ];
  $acc['update_any']['users'] = [];
  $acc['update_any']['permissions'] = [];

  $acc['delete_any']['roles'] = [
    'admin',
  ];
  $acc['delete_any']['users'] = [];
  $acc['delete_any']['permissions'] = [];

  $acc['purge_any']['roles'] = [
    'admin',
  ];
  $acc['purge_any']['users'] = [];
  $acc['purge_any']['permissions'] = [];

  $acc['update_own']['users'] = [];
  $acc['update_own']['permissions'] = [];

  $acc['delete_own']['roles'] = [];
  $acc['delete_own']['users'] = [];
  $acc['delete_own']['permissions'] = [];

  $acc['administer']['roles'] = [];
  $acc['administer']['users'] = [];
  $acc['administer']['permissions'] = [];

  $acc['test']['roles'] = [
    'verkkolomake_hallinnoija',
  ];
  $acc['test']['users'] = [];
  $acc['test']['permissions'] = [];

  $acc['configuration']['roles'] = [];
  $acc['configuration']['users'] = [];
  $acc['configuration']['permissions'] = [];

  if (isset($thirdPartySettings["login_type"])) {
    // And then per login type.
    switch ($thirdPartySettings["login_type"]) {
      // Strong auth.
      case '2':

        $acc['create']['roles'] = [
          'helsinkiprofiili_vahva',
          'admin',
        ];

        $acc['update_own']['roles'] = [
          'helsinkiprofiili_vahva',
        ];

        $acc['view_own']['roles'] = [
          'helsinkiprofiili_vahva',
        ];

        break;

      // Weak auth.
      case '1':
        $acc['create']['roles'] = [
          'helsinkiprofiili_heikko',
          'admin',
        ];

        $acc['update_own']['roles'] = [
          'helsinkiprofiili_heikko',
        ];
        $acc['view_own']['roles'] = [
          'helsinkiprofiili_heikko',
        ];
        break;

      // All other cases.
      default:
        $acc['create']['roles'] = [
          'anonymous',
        ];
        break;
    }
  }

  // Set rules.
  $entity->setAccessRules($acc);
}

/**
 * Implements hook_entity_insert().
 */
function webform_formtool_handler_webform_insert(Webform $entity) {

  /** @var \Drupal\webform\Plugin\WebformHandlerManagerInterface $handler_manager */
  $handler_manager = \Drupal::service('plugin.manager.webform.handler');

  // Create webform handler config.
  $handler_configuration = [
    'id' => 'formtool_webform_handler',
    'label' => 'Form Tool Handler',
    'handler_id' => 'formtool_webform_handler',
    'status' => TRUE,
    'weight' => 0,
    'settings' => [],
    'conditions' => [],
  ];
  try {
    /** @var \Drupal\webform\Plugin\WebformHandlerInterface $handler */
    $handler = $handler_manager->createInstance('formtool_webform_handler', $handler_configuration);

    // Must set original id so that the webform can be resaved.
    $entity->setOriginalId($entity->id());

    // Add webform handler which triggers Webform::save().
    $entity->addWebformHandler($handler);

  }
  catch (PluginException $e) {
    \Drupal::messenger()
      ->addError('Failed adding from tool handler automatically to a webform');
  }
}

/**
 * Implements hook_entity_type_alter().
 */
function webform_formtool_handler_entity_type_alter(array &$entity_types) {
  // @todo why is this not used?
  $entity_types['webform_submission']->setStorageClass('Drupal\webform_formtool_handler\FormToolSubmissionStorage');
}

/**
 * Implements hook_entity_type_build().
 */
function webform_formtool_handler_entity_type_build(array &$entity_types) {
  // @todo for some reason this hook does not invoke at all, so probabley this is not used.
  $entity_types['webform_submission']->setHandlerClass('access', 'Drupal\webform_formtool_handler\FormToolWsAccessHandler');
}
