<?php

/**
 * @file
 * Contains install functions for Form Tool Base Config.
 */

/**
 * Implements hook_install().
 *
 * Install HDBT and HDBT admin themes and make them as default themes.
 */
function form_tool_config_install() {
  \Drupal::service('theme_installer')->install(['form_tool_admin']);
  $system_theme = \Drupal::configFactory()->getEditable('system.theme');
  $system_theme->set('default', 'hdbt')->set('admin', 'form_tool_admin')->save();
}
