<?php
use Drupal\Core\Form\FormStateInterface;

/**
 * @file
 * Provides an example that shows how to create a Webform composite.
 */

module_load_include('inc', 'webform', 'includes/webform.theme.template');

/**
 * Implements hook_theme().
 */
function form_tool_contact_info_theme() {
  return [
    'form_tool_contact_info' => [
      'render element' => 'element',
    ],
  ];
}

/**
 * Prepares variables for webform example composite templates.
 *
 * Default template: webform-example-composite.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - element: An associative array containing the properties of the element.
 */
function template_preprocess_form_tool_contact_info(array &$variables) {
  // Here you can get the composite element and alter it.
  _template_preprocess_webform_composite($variables);
}


/**
 * Implements hook_form_FORM_ID_alter().
 *
 * @see admin/structure/webform/manage/{webform}/element/{element_key}/edit
 */
function form_tool_contact_info_form_webform_ui_element_form_alter(array &$form, FormStateInterface $form_state) {
  if ($form['properties']['type']['#value'] === 'form_tool_contact_info') {
    $options = array();
    $options['email'] = t('Email');
    $options['postal'] = t('Postal Delivery');
    $options['cod'] = t('Cash on Delivery');
    $options['pickup'] = t('Pickup');
    $form['custom_values']['form_tool_contact_info']['delivery_type'] = [
      '#type' => 'checkboxes',
      '#title' => t('Delivery Method'),
      '#options' => $options,
      '#default_value' => array_keys($options),
    ];
    foreach (array_keys($form['actions']) as $action) {
      if ($action != 'preview' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {
        $form['actions']['submit']['#submit'][] = 'form_tool_contact_info_submit';
      }
    }
  }
}

function form_tool_contact_info_submit(&$form, \Drupal\Core\Form\FormStateInterface $form_state) {
  //  $account = $form_state->getFormObject()->getEntity();
  $emailtrue = $form['custom_values']['form_tool_contact_info']['delivery_type']['email']['#checked'];
  $postaltrue = $form['custom_values']['form_tool_contact_info']['delivery_type']['postal']['#checked'];
  $codtrue = $form['custom_values']['form_tool_contact_info']['delivery_type']['cod']['#checked'];
  $pickuptrue = $form['custom_values']['form_tool_contact_info']['delivery_type']['pickup']['#checked'];
  $optionArray = [];
  if ($emailtrue == 1)
    $optionArray['email'] = t('Email');
  if ($postaltrue == 1)
    $optionArray['postal'] = t('Postal Delivery');
  if ($codtrue == 1)
    $optionArray['cod'] = t('Cash on Delivery');
  if ($pickuptrue == 1)
    $optionArray['pickup'] = t('Pickup');
/*    echo $form_state->getValues();
// $form_state->setValue(array('properties','delivery_method__options'), $optionArray);
  echo '<pre>';
  $node = $form_state->getFormObject();


  print_r(array_keys($form_state->getValues()));
  $i = 0;
  foreach ($form_state->getValues() as $formette){
    echo '---
    ';
    echo $i++.': ';
    print_r(array_keys($formette));
    $j = 0;

      foreach ($formette as $formettes){
        echo '
        ';
        echo $j++.': ';
        print_r(array_keys($formettes));

      }
  }
//  print_r($form_state->getValue(array('properties','delivery_method__options')));
  die();
   //  $form_state->setValue('delivery_method__options', 'email');
*/
}
