<?php
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Config\Entity\ThirdPartySettingsInterface;

/**
 * @param $sector The name of the sector.
 *
 * @return string The url to the privacy policy link for the sector.
 */
function _form_tool_webform_parameters_get_default_privacy_policy_link($formsettings) {
  $language = \Drupal::languageManager()->getCurrentLanguage()->getId();
  if ($language == 'fi') {
    if (array_key_exists('privacy_policy', $formsettings)) {
      return $formsettings['privacy_policy'];
    } else {
      // TODO Figure out default links for $formsettings['sectors'] when sectors get defined
      return 'https://asiakirjajulkisuus.hel.fi/';
    }
  } else if ($language == 'sv') {
    if (array_key_exists('privacy_policy_sv', $formsettings)) {
      return $formsettings['privacy_policy_sv'];
    } else {
      // TODO Figure out default links for $formsettings['sectors'] when sectors get defined
      return 'https://asiakirjajulkisuus.hel.fi/';
    }
  } else if ($language == 'en') {
    if (array_key_exists('privacy_policy_en', $formsettings)) {
      return $formsettings['privacy_policy_en'];
    } else {
      // TODO Figure out default links for $formsettings['sectors'] when sectors get defined
      return 'https://asiakirjajulkisuus.hel.fi/';
    }
  } else if ($language == 'ru') {
    if (array_key_exists('privacy_policy_ru', $formsettings)) {
      return $formsettings['privacy_policy_ru'];
    } else {
      // TODO Figure out default links for $formsettings['sectors'] when sectors get defined
      return 'https://asiakirjajulkisuus.hel.fi/';
    }
  }
  return 'https://asiakirjajulkisuus.hel.fi/';
}

/**
 * @file
 * Primary module hooks for Hel.fi Form Tool Webform Parameters module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */
function form_tool_webform_parameters_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (!\Drupal::service('router.admin_context')->isAdminRoute()) {
    if (array_key_exists('#webform_id', $form)) {
      $webform = \Drupal\webform\Entity\Webform::load($form['#webform_id']);
      $formsettings = $webform->getThirdPartySettings('form_tool_webform_parameters');

      $privacy_policy_link = _form_tool_webform_parameters_get_default_privacy_policy_link($formsettings);
      $privacy_policy_string = t('I have read and approved') . ' <a href="' . $privacy_policy_link . '">' . t('the privacy policy') . '</a>.';
      $form['privacy_policy_wrapper'] = array(
        '#type' => 'webform_section',
        '#title' => t('Privacy Policy'),
      );
      $form['privacy_policy_wrapper']['privacy_policy_acceptance'] = array(
        '#type' => 'checkbox',
        '#title' => $privacy_policy_string,
        '#required' => TRUE,
      );
    }
  }
  if ($form_id == 'webform_settings_form' || $form_id == 'webform_add_form' || $form_id == 'webform_duplicate_form') {
    $bundle = $form_state->getFormObject()->getEntity();
    // Because hidden by default.
    $form['third_party_settings']['#access'] = true;
    $form['third_party_settings']['#tree'] = TRUE;

    $form['third_party_settings']['#title'] = t('Form Pre-Information');

    $form['third_party_settings']['form_tool_webform_parameters'] = [
        '#type' => 'details',
        '#title' => t('Form Pre-Information'),
        '#open' => true,
        '#input' => false,
      ];

    $form['third_party_settings']['form_tool_webform_parameters']['owner'] = [
      '#type' => 'textfield',
      '#title' => t('Person responsible (Owner)'),
      '#default_value' => $bundle->getThirdPartySetting('form_tool_webform_parameters', 'owner'),
      '#required' => TRUE,
    ];

    $form['third_party_settings']['form_tool_webform_parameters']['form_code'] = [
      '#type' => 'textfield',
      '#title' => t('Form short code used to identify submissions.'),
      '#default_value' => $bundle->getThirdPartySetting('form_tool_webform_parameters', 'form_code'),
      '#required' => TRUE,
      '#size' => 15,
      '#maxlength' => 20,
    ];

    $form['third_party_settings']['form_tool_webform_parameters']['sector'] = [
      '#type' => 'textfield',
      '#title' => t('The sector that handles the form data'),
      '#default_value' => $bundle->getThirdPartySetting('form_tool_webform_parameters', 'sector'),
      '#required' => TRUE,
    ];

    $form['third_party_settings']['form_tool_webform_parameters']['ad_group'] = [
      '#type' => 'textfield',
      '#title' => t('AD Group of the handlers of form data'),
      '#default_value' => $bundle->getThirdPartySetting('form_tool_webform_parameters', 'ad_group'),
      '#required' => FALSE,
    ];

    $form['third_party_settings']['form_tool_webform_parameters']['postal_address'] = [
      '#type' => 'textarea',
      '#title' => t('Postal address for paper form delivery'),
      '#default_value' => $bundle->getThirdPartySetting('form_tool_webform_parameters', 'postal_adress'),
      '#required' => FALSE,
    ];

    $form['third_party_settings']['form_tool_webform_parameters']['privacy_policy'] = [
      '#type' => 'textfield',
      '#title' => t('URL of Privacy Policy (Finnish)'),
      '#description' => t('If left empty, will use the default privacy policy from sector'),
      '#placeholder' => t('https://asiakirjajulkisuus.hel.fi/'),
      '#default_value' => $bundle->getThirdPartySetting('form_tool_webform_parameters', 'privacy_policy'),
      '#required' => FALSE,
    ];

    $form['third_party_settings']['form_tool_webform_parameters']['privacy_policy_sv'] = [
      '#type' => 'textfield',
      '#title' => t('URL of Privacy Policy (Swedish)'),
      '#description' => t('If left empty, will use the default privacy policy from sector'),
      '#placeholder' => t('https://asiakirjajulkisuus.hel.fi/'),
      '#default_value' => $bundle->getThirdPartySetting('form_tool_webform_parameters', 'privacy_policy_sv'),
      '#required' => FALSE,
    ];
    $form['third_party_settings']['form_tool_webform_parameters']['privacy_policy_en'] = [
      '#type' => 'textfield',
      '#title' => t('URL of Privacy Policy (English)'),
      '#description' => t('If left empty, will use the default privacy policy from sector'),
      '#placeholder' => t('https://asiakirjajulkisuus.hel.fi/'),
      '#default_value' => $bundle->getThirdPartySetting('form_tool_webform_parameters', 'privacy_policy_en'),
      '#required' => FALSE,
    ];
    $form['third_party_settings']['form_tool_webform_parameters']['privacy_policy_ru'] = [
      '#type' => 'textfield',
      '#title' => t('URL of Privacy Policy (Russian)'),
      '#description' => t('If left empty, will use the default privacy policy from sector'),
      '#placeholder' => t('https://asiakirjajulkisuus.hel.fi/'),
      '#default_value' => $bundle->getThirdPartySetting('form_tool_webform_parameters', 'privacy_policy_ru'),
      '#required' => FALSE,
    ];

    $form['third_party_settings']['form_tool_webform_parameters']['login_type'] = [
      '#type' => 'radios',
      '#title' => t('Login requirements'),
      '#options' => [
        '0' => t('No Authentication'),
        '1' => t('Weak Authentication'),
        '2' => t('Strong Authentication'),
      ],
      '#required' => FALSE,
      '#default_value' => $bundle->getThirdPartySetting('form_tool_webform_parameters', 'login_type')
    ];

    $form['third_party_settings']['form_tool_webform_parameters']['sensitive'] = [
      '#type' => 'radios',
      '#title' => t('Does the form contain sensitive information'),
      '#options' => [
        '1' => t('Yes'),
        '0' => t('No'),
      ],
      '#required' => TRUE,
      '#default_value' => $bundle->getThirdPartySetting('form_tool_webform_parameters', 'sensitive')
    ];
  }
}
